//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.07 at 01:40:36 AM CST 
//


package com.bankaya.wsdl.pokemon;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="pokemonBaseExperience" type="{http://bankaya.com/wsdl/pokemon}pokemonBaseExperience"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pokemonBaseExperience"
})
@XmlRootElement(name = "getBaseExperienceResponse")
public class GetBaseExperienceResponse {

    @XmlElement(required = true)
    protected PokemonBaseExperience pokemonBaseExperience;

    /**
     * Gets the value of the pokemonBaseExperience property.
     * 
     * @return
     *     possible object is
     *     {@link PokemonBaseExperience }
     *     
     */
    public PokemonBaseExperience getPokemonBaseExperience() {
        return pokemonBaseExperience;
    }

    /**
     * Sets the value of the pokemonBaseExperience property.
     * 
     * @param value
     *     allowed object is
     *     {@link PokemonBaseExperience }
     *     
     */
    public void setPokemonBaseExperience(PokemonBaseExperience value) {
        this.pokemonBaseExperience = value;
    }

}
