//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.07 at 01:40:36 AM CST 
//


package com.bankaya.wsdl.pokemon;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="pokemonLocalAreaEncounters" type="{http://bankaya.com/wsdl/pokemon}pokemonLocalAreaEncounters"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pokemonLocalAreaEncounters"
})
@XmlRootElement(name = "getLocalAreaEncountersResponse")
public class GetLocalAreaEncountersResponse {

    @XmlElement(required = true)
    protected PokemonLocalAreaEncounters pokemonLocalAreaEncounters;

    /**
     * Gets the value of the pokemonLocalAreaEncounters property.
     * 
     * @return
     *     possible object is
     *     {@link PokemonLocalAreaEncounters }
     *     
     */
    public PokemonLocalAreaEncounters getPokemonLocalAreaEncounters() {
        return pokemonLocalAreaEncounters;
    }

    /**
     * Sets the value of the pokemonLocalAreaEncounters property.
     * 
     * @param value
     *     allowed object is
     *     {@link PokemonLocalAreaEncounters }
     *     
     */
    public void setPokemonLocalAreaEncounters(PokemonLocalAreaEncounters value) {
        this.pokemonLocalAreaEncounters = value;
    }

}
