//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.07 at 01:40:36 AM CST 
//


package com.bankaya.wsdl.pokemon;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bankaya.wsdl.pokemon package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bankaya.wsdl.pokemon
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetNameRequest }
     * 
     */
    public GetNameRequest createGetNameRequest() {
        return new GetNameRequest();
    }

    /**
     * Create an instance of {@link GetNameResponse }
     * 
     */
    public GetNameResponse createGetNameResponse() {
        return new GetNameResponse();
    }

    /**
     * Create an instance of {@link PokemonName }
     * 
     */
    public PokemonName createPokemonName() {
        return new PokemonName();
    }

    /**
     * Create an instance of {@link GetIdRequest }
     * 
     */
    public GetIdRequest createGetIdRequest() {
        return new GetIdRequest();
    }

    /**
     * Create an instance of {@link GetIdResponse }
     * 
     */
    public GetIdResponse createGetIdResponse() {
        return new GetIdResponse();
    }

    /**
     * Create an instance of {@link PokemonId }
     * 
     */
    public PokemonId createPokemonId() {
        return new PokemonId();
    }

    /**
     * Create an instance of {@link GetLocalAreaEncountersRequest }
     * 
     */
    public GetLocalAreaEncountersRequest createGetLocalAreaEncountersRequest() {
        return new GetLocalAreaEncountersRequest();
    }

    /**
     * Create an instance of {@link GetLocalAreaEncountersResponse }
     * 
     */
    public GetLocalAreaEncountersResponse createGetLocalAreaEncountersResponse() {
        return new GetLocalAreaEncountersResponse();
    }

    /**
     * Create an instance of {@link PokemonLocalAreaEncounters }
     * 
     */
    public PokemonLocalAreaEncounters createPokemonLocalAreaEncounters() {
        return new PokemonLocalAreaEncounters();
    }

    /**
     * Create an instance of {@link GetHeldItemsRequest }
     * 
     */
    public GetHeldItemsRequest createGetHeldItemsRequest() {
        return new GetHeldItemsRequest();
    }

    /**
     * Create an instance of {@link GetHeldItemsResponse }
     * 
     */
    public GetHeldItemsResponse createGetHeldItemsResponse() {
        return new GetHeldItemsResponse();
    }

    /**
     * Create an instance of {@link PokemonHeldItems }
     * 
     */
    public PokemonHeldItems createPokemonHeldItems() {
        return new PokemonHeldItems();
    }

    /**
     * Create an instance of {@link GetAbilitiesRequest }
     * 
     */
    public GetAbilitiesRequest createGetAbilitiesRequest() {
        return new GetAbilitiesRequest();
    }

    /**
     * Create an instance of {@link GetAbilitiesResponse }
     * 
     */
    public GetAbilitiesResponse createGetAbilitiesResponse() {
        return new GetAbilitiesResponse();
    }

    /**
     * Create an instance of {@link PokemonAbilities }
     * 
     */
    public PokemonAbilities createPokemonAbilities() {
        return new PokemonAbilities();
    }

    /**
     * Create an instance of {@link GetBaseExperienceRequest }
     * 
     */
    public GetBaseExperienceRequest createGetBaseExperienceRequest() {
        return new GetBaseExperienceRequest();
    }

    /**
     * Create an instance of {@link GetBaseExperienceResponse }
     * 
     */
    public GetBaseExperienceResponse createGetBaseExperienceResponse() {
        return new GetBaseExperienceResponse();
    }

    /**
     * Create an instance of {@link PokemonBaseExperience }
     * 
     */
    public PokemonBaseExperience createPokemonBaseExperience() {
        return new PokemonBaseExperience();
    }

}
