//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.07 at 01:40:36 AM CST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://bankaya.com/wsdl/pokemon", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.bankaya.wsdl.pokemon;
